project:
  type: website
  output-dir: docs
  
website:
  title: "Shane A. Scaggs"
  navbar:
    search: true
    background: '#000000'
    foreground: '#ffffff'
    left:
      - href: index.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: posts/posts.qmd
        text: Blog
      - gallery.qmd
    right:
      - icon: "twitter"
        href: "https://twitter.com/shaneascaggs"
      - icon: "github"
        href: "https://github.com/sascaggs"
      - text: "{{< iconify ri:bluesky-fill >}}"
        href: "https://bsky.app/profile/sascaggs.bsky.social"
      - text: "{{< iconify academicons:google-scholar-square >}}"
        href: "https://scholar.google.com/citations?user=CtWNkOkAAAAJ&hl=en&oi=ao"
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Shane A. Scaggs"

format:
  html:
    css: styles.css
    toc: false

editor: source

collections: 
  posts:
    categories: true 
    sort: "date desc"
    index: 
      title: "Blog"
      description: "Posts and updates"